# Generated by Django 5.2.4 on 2025-07-20 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', '일일 리포트'), ('weekly', '주간 리포트'), ('monthly', '월간 리포트'), ('story', '스토리별 리포트')], max_length=20, verbose_name='리포트 타입')),
                ('date_from', models.DateField(verbose_name='시작 날짜')),
                ('date_to', models.DateField(verbose_name='종료 날짜')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='총 세션 수')),
                ('completed_sessions', models.PositiveIntegerField(default=0, verbose_name='완료된 세션 수')),
                ('average_completion_time', models.DurationField(blank=True, null=True, verbose_name='평균 완료 시간')),
                ('average_attempts', models.FloatField(default=0.0, verbose_name='평균 시도 횟수')),
                ('average_score', models.FloatField(default=0.0, verbose_name='평균 점수')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('report_data', models.JSONField(default=dict, verbose_name='상세 리포트 데이터')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.story', verbose_name='대상 스토리')),
            ],
            options={
                'verbose_name': '학습 리포트',
                'verbose_name_plural': '학습 리포트',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='사용자 세션 ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='액션 타입')),
                ('action_data', models.JSONField(default=dict, verbose_name='액션 데이터')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='시간')),
                ('user_agent', models.TextField(blank=True, verbose_name='사용자 에이전트')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story', verbose_name='스토리')),
            ],
            options={
                'verbose_name': '학습 분석',
                'verbose_name_plural': '학습 분석 데이터',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session_id', 'story'], name='progress_le_session_012860_idx'), models.Index(fields=['action_type', 'timestamp'], name='progress_le_action__139eb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='사용자 세션 ID')),
                ('completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='시도 횟수')),
                ('completion_time', models.DurationField(blank=True, null=True, verbose_name='완료 시간')),
                ('submitted_code', models.TextField(blank=True, verbose_name='제출 코드')),
                ('hints_used', models.PositiveIntegerField(default=0, verbose_name='사용한 힌트 수')),
                ('total_execution_time', models.FloatField(default=0.0, verbose_name='총 실행 시간(초)')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='오류 발생 횟수')),
                ('successful_runs', models.PositiveIntegerField(default=0, verbose_name='성공한 실행 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시작일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story', verbose_name='스토리')),
            ],
            options={
                'verbose_name': '학습 진행률',
                'verbose_name_plural': '학습 진행률 관리',
                'ordering': ['-updated_at'],
                'unique_together': {('session_id', 'story')},
            },
        ),
    ]
