# Generated by Django 5.2.4 on 2025-07-20 07:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '스토리 카테고리',
                'verbose_name_plural': '스토리 카테고리',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='스토리 내용')),
                ('objectives', models.TextField(verbose_name='학습 목표')),
                ('difficulty', models.IntegerField(choices=[(1, '입문'), (2, '기초'), (3, '중급'), (4, '고급'), (5, '전문가')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='난이도')),
                ('order', models.PositiveIntegerField(verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('initial_world_data', models.JSONField(default=dict, help_text='JSON 형태의 초기 게임 월드 설정', verbose_name='초기 월드 데이터')),
                ('solution_code', models.TextField(blank=True, help_text='문제 해결을 위한 예시 코드', verbose_name='솔루션 코드')),
                ('image_url', models.URLField(blank=True, verbose_name='스토리 이미지 URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.storycategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '스토리',
                'verbose_name_plural': '스토리 관리',
                'ordering': ['category__order', 'order'],
                'unique_together': {('category', 'order')},
            },
        ),
    ]
