# Generated by Django 5.2.4 on 2025-07-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['category', 'order'], name='story_story_categor_b1474c_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['is_active'], name='story_story_is_acti_febe7b_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['difficulty'], name='story_story_difficu_ed2376_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['created_at'], name='story_story_created_4db24d_idx'),
        ),
    ]
