# Generated by Django 5.2.4 on 2025-07-20 07:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='에셋명')),
                ('asset_type', models.CharField(choices=[('character', '캐릭터'), ('item', '아이템'), ('mob', '몹'), ('wall', '벽'), ('background', '배경')], max_length=20, verbose_name='에셋 타입')),
                ('image_url', models.URLField(verbose_name='이미지 URL')),
                ('properties', models.JSONField(default=dict, verbose_name='속성')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '게임 에셋',
                'verbose_name_plural': '게임 에셋 관리',
                'ordering': ['asset_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='세션 ID')),
                ('world_data', models.JSONField(default=dict, verbose_name='월드 상태')),
                ('character_data', models.JSONField(default=dict, verbose_name='캐릭터 상태')),
                ('submitted_code', models.TextField(blank=True, verbose_name='제출 코드')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('last_action_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='마지막 액션 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='시도 횟수')),
                ('hints_used', models.PositiveIntegerField(default=0, verbose_name='힌트 사용 횟수')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story', verbose_name='스토리')),
            ],
            options={
                'verbose_name': '게임 세션',
                'verbose_name_plural': '게임 세션 관리',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GameAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('move', '이동'), ('turn_left', '왼쪽 회전'), ('pick', '아이템 줍기'), ('put', '아이템 놓기'), ('attack', '공격'), ('eat', '아이템 먹기'), ('say', '말하기'), ('open_door', '문 열기')], max_length=20, verbose_name='액션 타입')),
                ('action_data', models.JSONField(default=dict, verbose_name='액션 데이터')),
                ('character_state_before', models.JSONField(default=dict, verbose_name='액션 전 캐릭터 상태')),
                ('character_state_after', models.JSONField(default=dict, verbose_name='액션 후 캐릭터 상태')),
                ('world_state_snapshot', models.JSONField(default=dict, verbose_name='월드 상태 스냅샷')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='실행 시간')),
                ('execution_time_ms', models.PositiveIntegerField(default=0, verbose_name='실행 시간(ms)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='game.gamesession', verbose_name='게임 세션')),
            ],
            options={
                'verbose_name': '게임 액션',
                'verbose_name_plural': '게임 액션 로그',
                'ordering': ['-timestamp'],
            },
        ),
    ]
