# Generated by Django 5.2.4 on 2025-07-20 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('story', '0002_story_story_story_categor_b1474c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.story', verbose_name='스토리'),
        ),
    ]
